In [63]:
import numpy as npy
import pandas as pds
from imblearn.over_sampling import SMOTE
%matplotlib inline

train_data = pds.read_csv('trainData.csv')

In [64]:
from collections import Counter
counts = Counter(train_data.TenYearCHD)
counts

Counter({0.0: 2864, 1.0: 528})

In [65]:
x_inputs = train_data.iloc[:, 0:15]
y_label = train_data.iloc[:, -1]

In [4]:
'''from imblearn.under_sampling import RandomUnderSampler
rand_us = RandomUnderSampler(random_state=0)
X_resampled, y_resampled = rand_us.fit_resample(x_inputs, y_label)'''

In [66]:
from imblearn.under_sampling import ClusterCentroids
cc_sample = ClusterCentroids(random_state=0)
X_resampled, y_resampled = cc_sample.fit_resample(x_inputs, y_label)

In [67]:
column = x_inputs.columns
cls = ['TenYearCHD']
attri = pds.DataFrame(X_resampled, columns = column)
label = pds.DataFrame(y_resampled, columns = cls)
new_data_sample = pds.concat([attri,label], axis = 1)

In [68]:
new_data_sample

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,0.285714,41.785714,1.714286,0.214286,1.857143,0.000000e+00,0.0,-5.551115e-17,3.469447e-18,203.357143,115.178571,74.392857,23.785714,73.714286,73.500000,0.0
1,0.000000,53.000000,2.000000,1.000000,10.000000,0.000000e+00,0.0,1.000000e+00,0.000000e+00,261.000000,136.000000,99.000000,21.000000,85.000000,94.000000,0.0
2,0.571429,42.714286,2.142857,1.000000,24.285714,3.469447e-18,0.0,1.428571e-01,3.469447e-18,309.714286,120.642857,79.357143,25.985714,65.285714,80.428571,0.0
3,0.400000,53.600000,1.600000,0.000000,0.000000,2.000000e-01,0.2,1.000000e+00,0.000000e+00,246.000000,151.300000,91.800000,27.580000,69.200000,53.400000,0.0
4,0.357143,42.285714,2.000000,0.071429,0.357143,0.000000e+00,0.0,2.857143e-01,3.469447e-18,198.357143,129.857143,87.571429,27.992857,78.428571,81.335714,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,0.000000,50.000000,1.000000,0.000000,0.000000,0.000000e+00,0.0,1.000000e+00,0.000000e+00,234.000000,143.000000,90.000000,29.400000,70.000000,86.000000,1.0
1052,0.000000,60.000000,3.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,328.000000,127.000000,70.000000,22.400000,75.000000,63.000000,1.0
1053,1.000000,43.000000,4.000000,1.000000,25.000000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,245.000000,126.000000,88.500000,23.200000,92.000000,73.900000,1.0
1054,1.000000,58.000000,1.000000,0.000000,0.000000,0.000000e+00,0.0,0.000000e+00,0.000000e+00,220.000000,143.000000,104.000000,29.900000,75.000000,87.000000,1.0
1055,0.000000,57.000000,1.000000,0.000000,0.000000,0.000000e+00,0.0,1.000000e+00,0.000000e+00,207.000000,175.000000,80.000000,20.900000,83.000000,75.000000,1.0

In [69]:
from sklearn.utils import shuffle
new_data_sample = shuffle(new_data_sample)
new_data_sample.reset_index(inplace=True, drop=True)
new_data_sample.head(20)

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1.000000,42.000000,3.00,1.00,2.500000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,256.000000,121.500000,74.000,23.600000,70.000000,115.0,1.0
1,1.000000,63.000000,1.00,0.00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.000000e+00,222.000000,159.000000,90.000,21.900000,80.000000,95.0,1.0
2,1.000000,44.000000,1.00,1.00,1.500000e+01,0.000000e+00,0.000000e+00,1.000000,0.000000e+00,232.000000,141.000000,104.000,27.400000,75.000000,85.1,1.0
3,1.000000,50.000000,4.00,0.00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,220.000000,114.000000,78.000,26.300000,79.000000,83.0,1.0
4,1.000000,38.000000,1.00,0.00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,203.000000,116.000000,81.000,30.200000,62.000000,80.0,1.0
5,0.000000,57.000000,3.00,1.00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,289.000000,142.000000,83.000,35.200000,68.000000,72.0,1.0
6,0.000000,56.000000,3.00,1.00,2.000000e+01,0.000000e+00,0.000000e+00,1.000000,0.000000e+00,325.000000,160.000000,97.500,23.400000,85.000000,86.0,1.0
7,0.000000,56.000000,4.00,0.00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.000000e+00,246.000000,136.000000,87.000,26.200000,80.000000,72.0,1.0
8,1.000000,66.000000,3.00,0.00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.000000e+00,182.000000,151.000000,88.000,25.200000,85.000000,80.0,1.0
9,1.000000,49.000000,1.00,1.00,2.000000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,247.000000,150.000000,88.000,27.900000,75.000000,74.0,1.0
10,1.000000,47.000000,4.00,0.00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.000000e+00,270.000000,152.500000,108.000,26.100000,90.000000,88.0,1.0
11,0.500000,57.750000,1.75,1.00,2.125000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,270.000000,132.375000,84.250,27.050000,85.750000,96.0,0.0
12,0.666667,40.833333,2.50,1.00,2.116667e+01,3.469447e-18,0.000000e+00,0.666667,3.469447e-18,261.833333,139.916667,91.500,31.833333,72.333333,66.0,0.0
13,0.000000,59.000000,1.00,0.00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.000000e+00,240.000000,155.500000,100.500,33.500000,72.000000,116.0,1.0
14,0.000000,55.000000,1.00,0.00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.000000e+00,232.000000,170.000000,92.000,26.100000,96.000000,74.0,1.0
15,0.250000,57.250000,2.25,0.25,1.750000e+00,2.500000e-01,0.000000e+00,0.750000,0.000000e+00,206.250000,159.500000,97.500,30.375000,74.750000,68.5,0.0
16,0.500000,36.000000,1.50,1.00,4.150000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,208.000000,121.000000,74.500,22.100000,95.500000,98.5,0.0
17,1.000000,65.500000,2.00,0.00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,229.750000,109.750000,67.375,24.550000,74.750000,72.5,0.0
18,0.300000,40.400000,2.70,0.00,-1.776357e-15,3.469447e-18,-4.336809e-19,0.200000,3.469447e-18,243.200000,126.500000,83.150,25.800000,68.100000,61.4,0.0
19,1.000000,68.000000,1.00,1.00,1.500000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,157.000000,106.000000,48.000,26.700000,65.000000,65.0,1.0

In [70]:
columns =(new_data_sample.columns)
x = ''
st = [x+y for y in columns]
st = ','.join([str(elem) for elem in st])
st

'male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD'

In [71]:
npy.savetxt('trainDataUnderSampleCC.csv', new_data_sample, delimiter=',', fmt='%f', newline='\n', header = st)